URI-encode destination filename when renaming
Otherwise, if new filename contained non-ASCII characters, like german
"ẞß", for example, error happened in HTTP.ts:39 (in `method` function,
on a line which says `const request = new Request(url, ...`):

TypeError: Request constructor: Cannot convert value in
record<ByteString, ByteString> branch of
(sequence<sequence<ByteString>> or record<ByteString, ByteString>) to
ByteString because the character at index 53 has value 1099 which is
greater than 255.